package com.minion.scaffold.showkase

import android.content.Context
import com.airbnb.android.showkase.models.Showkase

/**
 * The debug half of the component catalog's entry point.
 *
 * There are two of these — this one and the release stub in `src/release` — rather than one file
 * guarded by `BuildConfig.DEBUG`. The Showkase runtime is a `debugImplementation` and
 * `getBrowserIntent` is generated by a `kspDebug` processor, so neither symbol exists on a release
 * compile classpath: a runtime flag would not compile, and duplicating the object is what lets the
 * caller in `src/main` stay variant-agnostic.
 *
 * `getBrowserIntent` is generated into [ShowkaseRootModule]'s package, which is this one — hence
 * no import for it.
 */
internal object ComponentCatalog {

    /** Whether a catalog was compiled into this variant at all. */
    const val IS_AVAILABLE: Boolean = true

    /** Opens the Showkase browser. */
    fun open(context: Context) {
        context.startActivity(Showkase.getBrowserIntent(context))
    }
}
