package com.minion.scaffold.showkase

import android.os.Bundle
import androidx.activity.ComponentActivity
import com.airbnb.android.showkase.models.Showkase

/**
 * Opens the Showkase browser from its own home-screen icon, then finishes.
 *
 * A separate launcher rather than a button inside the app: the catalog is a developer tool, and a
 * developer entry point placed in the product UI is how it ends up shipping. `android:noHistory`
 * in the debug manifest keeps this trampoline out of the back stack.
 *
 * `getBrowserIntent` is generated by the Showkase processor into [ShowkaseRootModule]'s package,
 * which is this one — hence no import for it.
 */
class ShowkaseLauncherActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        startActivity(Showkase.getBrowserIntent(this))
        finish()
    }
}
