package com.minion.scaffold.core.emv.reference

/** An ISO 18245 merchant category: the code as it appears in tag `52`, and what it means. */
data class MerchantCategory(
    val code: String,
    val name: String,
)

/**
 * ISO 18245 merchant category code lookup for tag `52`.
 *
 * A working subset, not the full standard. ISO 18245 defines close to a thousand codes, the great
 * majority of which describe merchant types that do not accept QR payments; carrying all of them
 * would add a few hundred kilobytes of string constants to every install so that a handful of
 * users could see a slightly better label. The codes here are the ones that actually turn up on
 * QR payloads — retail, food, transport, utilities, health, education and professional services.
 *
 * An unlisted code returns null and is reported verbatim. That is the honest outcome: the code
 * itself is the information, and a wrong-but-confident label is worse than none.
 */
object MerchantCategoryCodes {

    private val byCode: Map<String, String> = mapOf(
        "0742" to "Veterinary Services",
        "0763" to "Agricultural Cooperatives",
        "0780" to "Landscaping and Horticultural Services",
        "1520" to "General Contractors",
        "1711" to "Heating, Plumbing and Air Conditioning",
        "1731" to "Electrical Contractors",
        "1750" to "Carpentry Contractors",
        "1799" to "Special Trade Contractors",
        "2741" to "Miscellaneous Publishing and Printing",
        "2791" to "Typesetting and Platemaking Services",
        "4111" to "Local and Suburban Commuter Transport",
        "4121" to "Taxicabs and Limousines",
        "4131" to "Bus Lines",
        "4214" to "Motor Freight Carriers and Trucking",
        "4215" to "Courier Services",
        "4225" to "Public Warehousing and Storage",
        "4411" to "Cruise Lines",
        "4511" to "Airlines and Air Carriers",
        "4582" to "Airports and Airport Terminals",
        "4722" to "Travel Agencies and Tour Operators",
        "4784" to "Tolls and Bridge Fees",
        "4789" to "Transportation Services",
        "4812" to "Telecommunication Equipment",
        "4814" to "Telecommunication Services",
        "4816" to "Computer Network and Information Services",
        "4821" to "Telegraph Services",
        "4899" to "Cable, Satellite and Pay Television",
        "4900" to "Utilities — Electric, Gas, Water, Sanitary",
        "5013" to "Motor Vehicle Supplies and New Parts",
        "5045" to "Computers, Peripherals and Software",
        "5065" to "Electrical Parts and Equipment",
        "5072" to "Hardware Equipment and Supplies",
        "5111" to "Stationery, Office Supplies, Printing and Writing Paper",
        "5122" to "Drugs, Drug Proprietaries and Druggists' Sundries",
        "5137" to "Uniforms and Commercial Clothing",
        "5169" to "Chemicals and Allied Products",
        "5192" to "Books, Periodicals and Newspapers",
        "5199" to "Nondurable Goods",
        "5200" to "Home Supply Warehouse Stores",
        "5211" to "Lumber and Building Materials Stores",
        "5231" to "Glass, Paint and Wallpaper Stores",
        "5251" to "Hardware Stores",
        "5261" to "Nurseries, Lawn and Garden Supply Stores",
        "5271" to "Mobile Home Dealers",
        "5300" to "Wholesale Clubs",
        "5309" to "Duty Free Stores",
        "5310" to "Discount Stores",
        "5311" to "Department Stores",
        "5331" to "Variety Stores",
        "5399" to "Miscellaneous General Merchandise",
        "5411" to "Grocery Stores and Supermarkets",
        "5422" to "Freezer and Locker Meat Provisioners",
        "5441" to "Candy, Nut and Confectionery Stores",
        "5451" to "Dairy Products Stores",
        "5462" to "Bakeries",
        "5499" to "Miscellaneous Food Stores — Convenience and Specialty",
        "5511" to "Car and Truck Dealers — Sales and Service",
        "5533" to "Automotive Parts and Accessories Stores",
        "5541" to "Service Stations",
        "5542" to "Automated Fuel Dispensers",
        "5551" to "Boat Dealers",
        "5571" to "Motorcycle Shops and Dealers",
        "5611" to "Men's and Boys' Clothing and Accessories Stores",
        "5621" to "Women's Ready-to-Wear Stores",
        "5631" to "Women's Accessory and Specialty Shops",
        "5641" to "Children's and Infants' Wear Stores",
        "5651" to "Family Clothing Stores",
        "5655" to "Sports and Riding Apparel Stores",
        "5661" to "Shoe Stores",
        "5691" to "Men's and Women's Clothing Stores",
        "5699" to "Miscellaneous Apparel and Accessory Shops",
        "5712" to "Furniture and Home Furnishings Stores",
        "5722" to "Household Appliance Stores",
        "5732" to "Electronics Stores",
        "5733" to "Music Stores — Instruments and Sheet Music",
        "5734" to "Computer Software Stores",
        "5735" to "Record Stores",
        "5811" to "Caterers",
        "5812" to "Eating Places and Restaurants",
        "5813" to "Drinking Places — Bars and Taverns",
        "5814" to "Fast Food Restaurants",
        "5815" to "Digital Goods — Media, Books, Movies, Music",
        "5816" to "Digital Goods — Games",
        "5817" to "Digital Goods — Applications",
        "5818" to "Digital Goods — Large Digital Goods Merchant",
        "5912" to "Drug Stores and Pharmacies",
        "5921" to "Package Stores — Beer, Wine and Liquor",
        "5941" to "Sporting Goods Stores",
        "5942" to "Book Stores",
        "5943" to "Stationery and Office Supply Stores",
        "5944" to "Jewelry, Watch, Clock and Silverware Stores",
        "5945" to "Hobby, Toy and Game Shops",
        "5946" to "Camera and Photographic Supply Stores",
        "5947" to "Gift, Card, Novelty and Souvenir Shops",
        "5948" to "Luggage and Leather Goods Stores",
        "5949" to "Sewing, Needlework, Fabric and Piece Goods Stores",
        "5964" to "Direct Marketing — Catalog Merchant",
        "5965" to "Direct Marketing — Combination Catalog and Retail",
        "5967" to "Direct Marketing — Inbound Teleservices",
        "5968" to "Direct Marketing — Continuity and Subscription",
        "5969" to "Direct Marketing — Other",
        "5970" to "Artist Supply and Craft Shops",
        "5977" to "Cosmetic Stores",
        "5983" to "Fuel Dealers",
        "5992" to "Florists",
        "5993" to "Cigar Stores and Stands",
        "5994" to "News Dealers and Newsstands",
        "5995" to "Pet Shops, Pet Food and Supplies",
        "5999" to "Miscellaneous and Specialty Retail Stores",
        "6010" to "Financial Institutions — Manual Cash Disbursements",
        "6011" to "Financial Institutions — Automated Cash Disbursements",
        "6012" to "Financial Institutions — Merchandise and Services",
        "6051" to "Non-Financial Institutions — Money Orders, Travelers Cheques",
        "6211" to "Security Brokers and Dealers",
        "6300" to "Insurance Sales, Underwriting and Premiums",
        "6513" to "Real Estate Agents and Managers — Rentals",
        "7011" to "Lodging — Hotels, Motels and Resorts",
        "7032" to "Sporting and Recreational Camps",
        "7210" to "Laundry, Cleaning and Garment Services",
        "7211" to "Laundries — Family and Commercial",
        "7216" to "Dry Cleaners",
        "7230" to "Beauty and Barber Shops",
        "7297" to "Massage Parlors",
        "7298" to "Health and Beauty Spas",
        "7299" to "Miscellaneous Personal Services",
        "7311" to "Advertising Services",
        "7333" to "Commercial Photography, Art and Graphics",
        "7338" to "Quick Copy, Reproduction and Blueprinting",
        "7342" to "Exterminating and Disinfecting Services",
        "7349" to "Cleaning, Maintenance and Janitorial Services",
        "7372" to "Computer Programming and Data Processing",
        "7392" to "Management, Consulting and Public Relations",
        "7393" to "Detective and Protective Agencies",
        "7399" to "Business Services",
        "7512" to "Automobile Rental Agency",
        "7523" to "Parking Lots and Garages",
        "7531" to "Automotive Body Repair Shops",
        "7538" to "Automotive Service Shops",
        "7542" to "Car Washes",
        "7622" to "Electronics Repair Shops",
        "7629" to "Electrical and Small Appliance Repair",
        "7699" to "Miscellaneous Repair Shops",
        "7832" to "Motion Picture Theaters",
        "7841" to "Video Tape Rental Stores",
        "7911" to "Dance Halls, Studios and Schools",
        "7922" to "Theatrical Producers and Ticket Agencies",
        "7929" to "Bands, Orchestras and Entertainers",
        "7932" to "Billiard and Pool Establishments",
        "7933" to "Bowling Alleys",
        "7941" to "Commercial Sports and Athletic Fields",
        "7991" to "Tourist Attractions and Exhibits",
        "7994" to "Video Game Arcades and Establishments",
        "7997" to "Membership Clubs and Private Golf Courses",
        "7999" to "Recreation Services",
        "8011" to "Doctors and Physicians",
        "8021" to "Dentists and Orthodontists",
        "8031" to "Osteopaths",
        "8041" to "Chiropractors",
        "8042" to "Optometrists and Ophthalmologists",
        "8043" to "Opticians and Eyeglasses",
        "8049" to "Podiatrists and Chiropodists",
        "8050" to "Nursing and Personal Care Facilities",
        "8062" to "Hospitals",
        "8071" to "Medical and Dental Laboratories",
        "8099" to "Medical Services and Health Practitioners",
        "8111" to "Legal Services and Attorneys",
        "8211" to "Elementary and Secondary Schools",
        "8220" to "Colleges, Universities and Professional Schools",
        "8241" to "Correspondence Schools",
        "8244" to "Business and Secretarial Schools",
        "8249" to "Vocational and Trade Schools",
        "8299" to "Educational Services",
        "8351" to "Child Care Services",
        "8398" to "Charitable and Social Service Organizations",
        "8641" to "Civic, Social and Fraternal Associations",
        "8651" to "Political Organizations",
        "8661" to "Religious Organizations",
        "8699" to "Membership Organizations",
        "8931" to "Accounting, Auditing and Bookkeeping Services",
        "8999" to "Professional Services",
        "9211" to "Court Costs and Alimony",
        "9222" to "Fines",
        "9223" to "Bail and Bond Payments",
        "9311" to "Tax Payments",
        "9399" to "Government Services",
        "9402" to "Postal Services — Government Only",
        "9405" to "Intra-Government Purchases",
    )

    /**
     * Every category in the table, ordered by code.
     *
     * Backs the create tool's MCC picker. [nameOf] stays because the two directions are not the
     * same problem: a picker can only offer what is listed, while a *scanned* payload can carry
     * any code in ISO 18245 and still has to be looked up.
     */
    val all: List<MerchantCategory> = byCode.map { (code, name) -> MerchantCategory(code, name) }

    /** The category name for [code], or null if it is not in the table. */
    fun nameOf(code: String): String? = byCode[code]
}
